[package]
name = "NScan"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.32", features = ["derive"] }
pnet = "0.35.0"
rand = "0.9.0"
cidr = "0.2.2"
colored = "3.0.0"
tokio = { version = "1.44.1", features = ["net", "macros", "rt", "sync"] }
